version: "3.9"
services:
  calculator:
    build:
      context: ..            # one level up, where run.py & app/ are
      dockerfile: docker/Dockerfile
    container_name: calculator_app
    ports:
      - "5000:5000"
    restart: always
